# Site settings
title: ğ“¹ğ“ªğ“¾ğ“µ ğ“«ğ“¸ğ“¾ğ“²ğ“°ğ“¾ğ“®
tagline: "paul bouigue est probablement votre pire Ã©tudiant"
url: "pual.cool"
author: "paul bouigue"

# Social
instagram: https://instagram.com/smexypual
vimeo: https://vimeo.com/pbouigue
mail: paul.bouigue@gmail.com

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
